.TH BOREDSERF 5 boredserf\-VERSION
.SH NAME
boredserf \- simple webkit-based browser
.SH COMPILE-TIME CONFIGURATION
Most \fBboredserf\fR configuration occurs in the \fIconfig.h\fR file before compilation. Loosely speaking, there are five sections: paths, utilities, parameters, custom code, and keymaps.
.TP
If the \fIconfig.h\fR file is deleted, it will be replaced by the default values in \fIconfig.def.h\fR.
.SS Paths
These paths specify files and directories where given resources may be read from and/or written to.
.SS Utilities
These are \fBexecv\fR(3) commands where the final command's standard output is used as input to change a \fBboredserf\fR setting. The final array item must be NULL. 
.TP
Unlike most shell commands, these do not undergo shell expansion before being read by the shell. Arguments may be explicitly split into different words by "placing", "them", "in", "different", "strings".
.TP
In addition to inherited environment values, the following are set from the current page loaded in the browser:
.TP
.B $BS_URI
The main URI for the page.
.TP
.B $BS_TITLE
The page's title.
.TP
.B $BS_TEXT
The page's plain text.
.TP
.B $BS_LINKS
A list of the page's HTML links.
.TP
.B $BS_SCRIPTS
A list of the non-inline scripts the page would retrieve.
.TP
.B $BS_STYLES
A list of the non-inline CSS files the page would retrieve.
.TP
.B $BS_IMAGES
A list of the images the page would retrieve.
.TP
.B $BS_HISTFILE
The path to the history file specified in \fIconfig.h\fR.
.SS Parameters
This array specifies \fBboredserf\fR's core parameters, which take a value of `struct Arg', which can be an int, a float, or a void*, plus a priority value that should not be modified here because it differentiates between config-file values, run-time values, and user-specified values.
.SS Custom Code
This is a general purpose section for code that doesn't fit elsewhere.
.SS Keymaps
To create your own keymaps, define an array of Key values similar to those in \fIconfig.def.h\fR and invoke that map with a function of \fIsetkeytree\fR and a value of \fI.v\ =\ <name\ of\ new\ keymap>\fR.
.SH CONTENT BLOCKER CONFIGURATION
The content blocker, located by default at \fI~/.config/boredserf/filter.rules\fR, can be configured in exactly the same manner as its status indicator is displayed.
.TP
The file may have up to one rule per line. Contiguous whitespace is ignored, but whitespace delimits fields. The available fields are:
.TP
.B request-uri \fR(optional)
also known in WebKit as `if-url'. This applies to each prospective request that the browser may load for each page. Note that rules with this field are not visible in \fBboredserf\fR but are still used to block content. Rudimentary regular expressions are allowed, except those including whitespace (although '%20' is not seen as whitespace).
.TP
.B browser-uri \fR(required)
also known in WebKit as `if-top-url'. This applies to the URI that would be seen in the navigation bar. \fBboredserf\fR's interactive editor will only recognize this field if it is a plain-text domain name. However, regular expressions will still be read and passed to WebKit.
.TP
.B first-party \fR(required)
a list of characters in [dcfivmsrpDCFIVMSRP]. As before, lowercase letters block connections, uppercase letters allow them, and absent characters inherit other rules.
.TP
.B third-party \fR(required)
same as \fIfirst-party\fP, above.
.TP
Later rules take precedence over earlier rules.
.TP
Lines beginning with a '#', optionally preceded by spaces and/or tabs, and lines with less than three or more than four fields, including blank lines, are ignored and may be used for comments.
.TP
For example,
.TP
.B * 1cfivmsrp 3cfivmsrp
will block all requests other than for documents, on all webpages.
.TP
.B suckless.org 1Is 3
where the 'I' will let you see the sophisticated imagery on suckless.org, but the lack of an 'I' after '3' means that images from third parties will be blocked due to the previous rule. The 's' will strip inline, script-like content from the main HTML document. Note that the `3' is mandatory even if all rules are to be inherited.
.TP
.B puppy * 1IMSR 3IMSR
will display images and media, which usually require scripts which in turn often use raw-type requests, for requests from any website that includes `puppy' in the request URI; neither the request-uri nor browser-uri fields are limited to domain names. Note, however, that the \fBboredserf\fR interface only sets domain names for the browser-uri and will not present other rules for editing.
.TP
.B http://[^/]*suckless\\\\\\\\.org/ * 1dcfivmsrp 3dcfivmsrp
will block all types of HTTP connections to a URI in a domain that matches 'suckless.org'. In effect, this requires all connections to such servers to be over HTTPS. Note that this is only a request made to the WebKit engine; it does not guarantee that no such connections will be made.
.TP
The \fBboredserf\fP content blocker uses the WebKit tool of the same name. See WebKit documentation for more details on what is possible.
